language: csharp
solution: pusher-dotnet-server.sln

matrix:
  include:
    - env: DOTNETCORE=1
      sudo: required
      mono: 4.4.2
      dotnet: 2.1.502
      os: linux
      dist: trusty

script:
  - sudo bash -x ./build.sh